#!/usr/bin/env python3
"""
build_web_impl.py — Minifica, comprime (gzip) e gera web_pages.h
Pode ser executado standalone: python3 tools/build_web_impl.py
Ou chamado pelo wrapper SCons (build_web.py) via PlatformIO extra_scripts.

Requer apenas Python stdlib (3.6+). Sem dependências externas.
"""

import re
import gzip
import io
import os
import sys
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────
ROOT     = Path(__file__).parent.parent
SRC_DIR  = ROOT / "web_src"
OUT_FILE = ROOT / "src" / "web" / "web_pages.h"


# ── Minifiers (stdlib apenas) ─────────────────────────────────────────────────

def minify_html(src):
    """Remove comentários HTML e colapsa whitespace entre tags."""
    src = re.sub(r'<!--.*?-->', '', src, flags=re.DOTALL)
    src = re.sub(r'>\s+<', '><', src)
    src = re.sub(r'\s{2,}', ' ', src)
    return src.strip()


def minify_css(src):
    """Remove comentários CSS e whitespace desnecessário."""
    # Remove blocos @font-face com PLACEHOLDER (não servem para nada compilados)
    src = re.sub(r'@font-face\s*\{[^}]*PLACEHOLDER[^}]*\}', '', src, flags=re.DOTALL)
    # Remove comentários /* ... */
    src = re.sub(r'/\*.*?\*/', '', src, flags=re.DOTALL)
    # Colapsa whitespace
    src = re.sub(r'\s{2,}', ' ', src)
    # Remove espaços em torno de operadores CSS
    src = re.sub(r'\s*([{}:;,>+~])\s*', r'\1', src)
    # Remove último ponto-e-vírgula antes de }
    src = re.sub(r';\}', '}', src)
    return src.strip()


def minify_js(src):
    """
    Minificação conservadora de JS usando apenas stdlib.
    Remove comentários de linha e blocos, colapsa whitespace.
    NOTA: Não remove strings — seguro para uso em produção embarcada.
    """
    # Remove comentários de bloco /* ... */ (cuidado com regex em strings)
    src = re.sub(r'/\*.*?\*/', '', src, flags=re.DOTALL)
    # Remove comentários de linha // ... com negative lookbehind em ':' para não
    # destruir URLs do tipo '://' que aparecem em strings (ex: WebSocket URL).
    src = re.sub(r'(?<!:)//[^\n]*', '', src)
    # Colapsa linhas em branco consecutivas
    src = re.sub(r'\n\s*\n', '\n', src)
    # Colapsa espaços/tabs
    src = re.sub(r'[ \t]+', ' ', src)
    # Remove espaços desnecessários em torno de alguns operadores
    src = re.sub(r' *([\n{};,=+\-*/<>!&|?:]) *', r'\1', src)
    return src.strip()


# ── Compressão ────────────────────────────────────────────────────────────────

def gzip_compress(data, level=9):
    """Comprime bytes com gzip. mtime=0 garante output determinístico."""
    buf = io.BytesIO()
    with gzip.GzipFile(fileobj=buf, mode='wb', compresslevel=level, mtime=0) as f:
        f.write(data)
    return buf.getvalue()


# ── Geração de array C ────────────────────────────────────────────────────────

def to_c_array(name, data):
    """Converte bytes em declaração C de array PROGMEM com constante de tamanho."""
    rows = [data[i:i+16] for i in range(0, len(data), 16)]
    hex_rows = ',\n  '.join(
        ', '.join('0x{:02x}'.format(b) for b in row)
        for row in rows
    )
    return (
        'const uint8_t {name}[] PROGMEM = {{\n  {hex}\n}};\n'
        'const size_t  {name}_len = {size};\n'
    ).format(name=name, hex=hex_rows, size=len(data))


# ── Pipeline principal ────────────────────────────────────────────────────────

ASSETS = [
    # (arquivo fonte, nome do array C, Content-Type, função de minificação)
    ('index.html', 'index_html_gz', 'text/html',             minify_html),
    ('style.css',  'style_css_gz',  'text/css',              minify_css),
    ('script.js',  'script_js_gz',  'application/javascript', minify_js),
]


def build():
    print('[build_web] Iniciando pipeline de build...')

    header_lines = [
        '// AUTO-GENERATED by tools/build_web_impl.py — NAO EDITAR\n',
        '// Fontes: web_src/index.html, web_src/style.css, web_src/script.js\n',
        '// Minificado + GZIP comprimido. Servir com Content-Encoding: gzip.\n\n',
        '#ifndef WEB_PAGES_H\n',
        '#define WEB_PAGES_H\n\n',
        '#include <Arduino.h>\n\n',
    ]

    total_original = 0
    total_compressed = 0

    for filename, array_name, _mime, minifier in ASSETS:
        src_path = SRC_DIR / filename
        if not src_path.exists():
            print('[build_web] ERRO: arquivo fonte nao encontrado: {}'.format(src_path))
            sys.exit(1)

        raw = src_path.read_text(encoding='utf-8')
        minified = minifier(raw)
        compressed = gzip_compress(minified.encode('utf-8'))

        total_original += len(raw)
        total_compressed += len(compressed)

        header_lines.append(to_c_array(array_name, compressed))
        header_lines.append('\n')

        print('[build_web]   {:12s}  {:6d} bytes raw  ->  {:5d} bytes minified  ->  {:5d} bytes gzip  ({:.0f}% reducao)'.format(
            filename,
            len(raw),
            len(minified),
            len(compressed),
            (1 - len(compressed) / len(raw)) * 100
        ))

    header_lines.append('#endif // WEB_PAGES_H\n')

    OUT_FILE.write_text(''.join(header_lines), encoding='utf-8')

    print('[build_web] Total: {} bytes -> {} bytes ({:.0f}% reducao)'.format(
        total_original, total_compressed,
        (1 - total_compressed / total_original) * 100
    ))
    print('[build_web] Gerado: {}'.format(OUT_FILE))


if __name__ == '__main__':
    build()
